var whiteList = {
    a:      ['style', 'class', 'target', 'href', 'title'],
    abbr:   ['style', 'class', 'title'],
    address: ['style', 'class'],
    area:   ['style', 'class', 'shape', 'coords', 'href', 'alt'],
    article: ['style', 'class'],
    aside:  ['style', 'class'],
    audio:  ['style', 'class', 'autoplay', 'controls', 'loop', 'preload', 'src'],
    b:      ['style', 'class'],
    bdi:    ['style', 'class', 'dir'],
    bdo:    ['style', 'class', 'dir'],
    big:    ['style', 'class'],
    blockquote: ['style', 'class', 'cite'],
    br:     ['style', 'class'],
    caption: ['style', 'class'],
    center: ['style', 'class'],
    cite:   ['style', 'class'],
    code:   ['style', 'class'],
    col:    ['style', 'class', 'align', 'valign', 'span', 'width'],
    colgroup: ['style', 'class', 'align', 'valign', 'span', 'width'],
    dd:     ['style', 'class'],
    del:    ['style', 'class', 'datetime'],
    details: ['style', 'class', 'open'],
    div:    ['style', 'class'],
    dl:     ['style', 'class'],
    dt:     ['style', 'class'],
    em:     ['style', 'class'],
    font:   ['style', 'class', 'color', 'size', 'face'],
    footer: ['style', 'class'],
    h1:     ['style', 'class'],
    h2:     ['style', 'class'],
    h3:     ['style', 'class'],
    h4:     ['style', 'class'],
    h5:     ['style', 'class'],
    h6:     ['style', 'class'],
    header: ['style', 'class'],
    hr:     ['style', 'class'],
    i:      ['style', 'class'],
    img:    ['style', 'class', 'src', 'alt', 'title', 'width', 'height'],
    ins:    ['style', 'class', 'datetime'],
    li:     ['style', 'class'],
    mark:   ['style', 'class'],
    nav:    ['style', 'class'],
    ol:     ['style', 'class'],
    p:      ['style', 'class'],
    pre:    ['style', 'class'],
    s:      ['style', 'class'],
    section:['style', 'class'],
    small:  ['style', 'class'],
    span:   ['style', 'class'],
    sub:    ['style', 'class'],
    sup:    ['style', 'class'],
    strong: ['style', 'class'],
    table:  ['style', 'class', 'width', 'border', 'align', 'valign'],
    tbody:  ['style', 'class', 'align', 'valign'],
    td:     ['style', 'class', 'width', 'colspan', 'align', 'valign'],
    tfoot:  ['style', 'class', 'align', 'valign'],
    th:     ['style', 'class', 'width', 'colspan', 'align', 'valign'],
    thead:  ['style', 'class', 'align', 'valign'],
    tr:     ['style', 'class', 'rowspan', 'align', 'valign'],
    tt:     ['style', 'class'],
    u:      ['style', 'class'],
    ul:     ['style', 'class'],
    video:  ['style', 'class', 'autoplay', 'controls', 'loop', 'preload', 'src', 'height', 'width']
};

var xss = require('xss');

module.exports = new xss.FilterXSS(whiteList);